const regularize = {
    title: 'Regularização de imóveis',
    imageUrl: 'http://placehold.it/1200x400',
    text: [
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati consectetur cupiditate cum assumenda deserunt quia similique delectus quo rerum? Voluptate harum totam doloremque vitae corrupti deserunt sequi magni nostrum eveniet nobis dolor, eius pariatur. Pariatur nostrum quisquam perspiciatis labore sed in alias ullam quo asperiores beatae, dolorum facere odio nemo cum vel quas esse optio officiis! Dignissimos animi laborum magnam sequi dolorum exercitationem odio deserunt libero commodi! Nam mollitia labore voluptatibus pariatur optio enim, repellendus consequatur nisi facilis explicabo nemo sunt, recusandae non libero exercitationem magnam sint officia tempore? Saepe voluptatem aperiam eum. Fuga aliquid assumenda voluptatibus, in quis reiciendis.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati consectetur cupiditate cum assumenda deserunt quia similique delectus quo rerum? Voluptate harum totam doloremque vitae corrupti deserunt sequi magni nostrum eveniet nobis dolor, eius pariatur. Pariatur nostrum quisquam perspiciatis labore sed in alias ullam quo asperiores beatae, dolorum facere odio nemo cum vel quas esse optio officiis! Dignissimos animi laborum magnam sequi dolorum exercitationem odio deserunt libero commodi! Nam mollitia labore voluptatibus pariatur optio enim, repellendus consequatur nisi facilis explicabo nemo sunt, recusandae non libero exercitationem magnam sint officia tempore? Saepe voluptatem aperiam eum. Fuga aliquid assumenda voluptatibus, in quis reiciendis.",
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati consectetur cupiditate cum assumenda deserunt quia similique delectus quo rerum? Voluptate harum totam doloremque vitae corrupti deserunt sequi magni nostrum eveniet nobis dolor, eius pariatur. Pariatur nostrum quisquam perspiciatis labore sed in alias ullam quo asperiores beatae, dolorum facere odio nemo cum vel quas esse optio officiis! Dignissimos animi laborum magnam sequi dolorum exercitationem odio deserunt libero commodi! Nam mollitia labore voluptatibus pariatur optio enim, repellendus consequatur nisi facilis explicabo nemo sunt, recusandae non libero exercitationem magnam sint officia tempore? Saepe voluptatem aperiam eum. Fuga aliquid assumenda voluptatibus, in quis reiciendis."
    ]
}

export default regularize